{% set version = "3.1.30" %}

package:
  name: gitpython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: 769c2d83e13f5d938b7688479da374c4e3d49f71549aaf462b646db9602ea6f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - gitdb >=4.0.1,<5
    - typing_extensions >=3.7.4.3

test:
  requires:
    - git
    - pip
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo
  commands:
    - pip check

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Git Library
  doc_url: http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
