{% set version = "3.1.20" %}

package:
  name: gitpython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/GitPython/GitPython-{{ version }}.tar.gz
  sha256: df0e072a200703a65387b0cfdf0466e3bab729c0458cf6b7349d0e9877636519

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - gitdb >=4.0.1,<5
    - typing_extensions

test:
  requires:
    - git
    - pip
  imports:
    - git
    - git.index
    - git.objects
    - git.objects.submodule
    - git.refs
    - git.repo
  commands:
    - pip check

about:
  home: https://github.com/gitpython-developers/GitPython
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Git Library
  doc_url: http://gitpython.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - xhochy
